# Pytorch basics for DL newbies


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/BoostcampAITech/lecture-note-python-basics-for-ai/blob/main/codes/pytorch/07_torch-study/torch_basics.ipynb)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



## numpy to tensor

In [ ]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [ ]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [ ]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())


torch.Size([2, 5])
2
torch.Size([2, 5])


### Array to Tensor

##### Data to tensor

In [ ]:
data = [[3, 5],[10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

##### ndArray to Tensor

In [ ]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### numpy like operations

In [ ]:
data = [[3, 5, 20],[10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [ ]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [ ]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [ ]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [ ]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [ ]:
x_data.shape

torch.Size([3, 3])

In [ ]:
x_data.dtype

torch.int64

In [ ]:
x_data.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda') # GPU 위에 올리기
x_data_cuda.device

device(type='cuda', index=0)

### Tensor handling

In [ ]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.2339, 0.2657],
         [0.6382, 0.2874],
         [0.8491, 0.6041]],

        [[0.9554, 0.2911],
         [0.6191, 0.7847],
         [0.9226, 0.9968]]])

In [ ]:
tensor_ex.view([-1, 6])

tensor([[0.2339, 0.2657, 0.6382, 0.2874, 0.8491, 0.6041],
        [0.9554, 0.2911, 0.6191, 0.7847, 0.9226, 0.9968]])

In [ ]:
tensor_ex.reshape([-1,6])

tensor([[0.2339, 0.2657, 0.6382, 0.2874, 0.8491, 0.6041],
        [0.9554, 0.2911, 0.6191, 0.7847, 0.9226, 0.9968]])

In [ ]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
b 
# 메모리가 연결되어 있어 a와 같이 1로 채워짐

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
b
# reshape은 view와 다르게 메모리 연결을 보장하지 않아 여전히 0으로 이루어짐

tensor([0., 0., 0., 0., 0., 0.])

In [ ]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()

tensor([[0.2447, 0.8872],
        [0.0616, 0.7094]])

In [ ]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [ ]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [ ]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

## tensor operations

torch.mm
- 행렬의 곱셈만 지원. vector의 내적 불가능.
- broadcasting을 지원하지 않는다. → Debug에서 유리하다.
- 추가적으로, batch 차원까지 연산을 지원해주지는 않는다. 딱, 2차원 행렬끼리의 곱만 연산가능하다.
 - ex. (3, 4) @ (4, 10) = (3, 10)
 
torch.dot
- 벡터의 내적만 지원. (numpy와는 다르게 행렬곱/행렬연산은 지원하지 않는다.). 

torch.matmul
- vector의 내적, 행렬의 연산 다 사용가능
- broadcasting을 지원한다. (debugging에서 불리한 포인트)

torch.bmm
- torch.mm과의 차이점은 mm은 2차원 행렬의 곱 연산만 지원하고,
- torch.bmm은 3차원 텐서의 곱 연산만 지원한다.
 - ex. (10, 5, 3) @ (10, 3, 2) = (10, 5, 2)

In [ ]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [ ]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
t1 + t2
# dimension이 안 맞음 (연산 불가)

RuntimeError: ignored

In [ ]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
t1.dot(t2)
# dot은 행렬곱 연산 지원 안 함 (벡터 연산만 가능)

RuntimeError: ignored

In [ ]:
t1.matmul(t2)


tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
a = torch.rand(10)
b = torch.rand(10)
a.dot(b)

tensor(1.9316)

In [ ]:
a

tensor([0.4210, 0.1164, 0.2325, 0.0466, 0.6991, 0.0688, 0.3203, 0.5432, 0.7147,
        0.6352])

In [ ]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)
# mm은 행렬곱 연산만 지원 (벡터 내적 연산 지원 안 함)

RuntimeError: ignored

In [ ]:
t1.matmul(t2)
# matmul은 둘 다 지원

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.3751, 0.8399],
        [0.9324, 0.6120],
        [0.8757, 0.8950],
        [0.1937, 0.5053],
        [0.6919, 1.0750]])

In [ ]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()

tensor([0.3751, 0.8399])

In [ ]:
a[1].mm(torch.unsqueeze(b,1))

tensor([[0.9324],
        [0.6120]])

In [ ]:
a[2].mm(torch.unsqueeze(b,1))

tensor([[0.8757],
        [0.8950]])

In [ ]:
a[3].mm(torch.unsqueeze(b,1))

tensor([[0.1937],
        [0.5053]])

In [ ]:
a[4].mm(torch.unsqueeze(b,1))

tensor([[0.6919],
        [1.0750]])

In [ ]:
a

tensor([[[1.3531e-01, 3.5853e-01, 4.8900e-01],
         [3.9741e-01, 7.2441e-01, 9.7338e-01]],

        [[5.8025e-01, 7.6109e-01, 8.3147e-01],
         [5.3116e-01, 1.7737e-01, 5.4100e-01]],

        [[4.2634e-01, 7.9389e-01, 9.5267e-01],
         [4.1376e-01, 8.8669e-01, 9.4741e-01]],

        [[5.5450e-04, 3.7155e-01, 2.1864e-01],
         [5.4796e-01, 8.7151e-02, 2.7493e-01]],

        [[4.4432e-01, 2.3579e-01, 9.0382e-01],
         [8.4430e-01, 8.7964e-01, 5.9045e-01]]])

## tensor operations for ML/DL formula

In [ ]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor


tensor([0.3458, 0.4224, 0.2318])

In [ ]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)

y_label

tensor([0, 4, 2, 4, 2, 2, 1, 4, 3, 3])

In [ ]:
torch.nn.functional.one_hot(y_label)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0]])

In [ ]:
torch.nn.functional.one_hot(y_label)


tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0]])

In [ ]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [ ]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## torch autogard

$$
y = w^2 \\ 
z = 10*y + 25 \\
z = 10*w^2 + 25 
$$

In [ ]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y + 50
z.backward()
w.grad

tensor(40.)

In [ ]:
w.grad

tensor(40.)

$$ Q = 3a^3 - b^2  $$

In [ ]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.]) # Q에 대한 외부 변화율
Q.backward(gradient=external_grad) # Q.backward()와 동일

a.grad 

tensor([36., 81.])

In [ ]:
b.grad

tensor([-12.,  -8.])

$$ \frac{\partial Q}{\partial a} = 9a^2 $$  

$$ \frac{\partial Q}{\partial b} = -2b $$

In [ ]:
a.grad

tensor([36., 81.])

In [ ]:
b.grad

tensor([-12.,  -8.])